version: '3'

services:
  server:
    build:
      context: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
    container_name: client_t
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
